### PR TITLE
225 deploy amber contracts to foucoco and test that it works

### LINKED ISSUE #225: deploy amber contracts to foucoco and test that it works
deploy amber contracts to foucoco and test that it works

amber compiled contracts:
[https://app.zenhub.com/files/428984346/5ba8448e-f9df-4eb1-b9ab-76010834a767/download](https://app.zenhub.com/files/428984346/5ba8448e-f9df-4eb1-b9ab-76010834a767/download)

amber compiled slippage curve:
[https://app.zenhub.com/files/428984346/f18f9044-057a-43f3-b8d8-4f88912403d2/download](https://app.zenhub.com/files/428984346/f18f9044-057a-43f3-b8d8-4f88912403d2/download)

amber deployment scripts:
[https://app.zenhub.com/files/428984346/b5e33e2d-68d1-48ee-a79f-b4454e54427d/download](https://app.zenhub.com/files/428984346/b5e33e2d-68d1-48ee-a79f-b4454e54427d/download)

deployment scripts were written for mumbai, so they cannot be used as is, however the deployment steps can be derived from them.

instead of regular erc20 tokens, we should use wrapped native tokens using our psp22pendulum contract found in our `pendulum-ink-wrapper` repo.

### PR DESCRIPTION
**Pull request by ashneverdawn**

### CODE REVIEW

**Review by ebma — COMMENTED** [review]
I tried doing the setup by following the steps you put in the README and updated it with my findings along the way.
I changed the directory structure and deduplicated some code to make it more straightforward to use.

However, it's not clear to me what this PR is supposed to achieve as it does not contain a description and the linked ticket #225 does not specify how we want to test the contracts. I think ideally we should first agree on a testing approach in a separate ticket.

**Comment by TorstenStueber** [comment]
The problem is that we didn't properly define yet what we need to do for testing and Hugo was exploring here. It makes sense to me and I will incorporate this into the latest changes that I added to wasm-deploy. They should make some of the setup here easier to reproduce.

**Comment by ebma** [comment]
Okay so you are picking some of the changes of this PR and applying it to another? Can you maybe link to the branch or commit so that it's easier to follow @TorstenStueber?

**Comment by TorstenStueber** [comment]
@ebma This is a current branch but does not include the tests yet: https://github.com/pendulum-chain/wasm-deploy/pull/19. However, it contains some of the other changes so that it should be easy to run wasm-deploy out of of the box for Nabla.

**Comment by TorstenStueber** [comment]
We can close this PR now as it has been replaced by https://github.com/pendulum-chain/wasm-deploy/pull/23

**Pull request closed without merging**
